### ISSUE TITLE
Does not follow symlinks

### ISSUE THREAD

**Issue by mradeschnig** [ukhas/js-logtail#11]
I really like this tool very much. But the I have one application which places the log-fiel in some other place at I thought to create a symlink to that location and logtail would present it like it would be in the tomcat subfolder.
I obviously make something wrong or the script does not follow symlinks. If I copy the file "data/logdaily.log" there it works fine. As well it seems it is not possible to put there some other absolute path to a file soemwhere else on the same server.

**Comment by danielrichman** [comment]
I believe that it does indeed follow symlinks: we use symlinks over at habitat.

When using symlinks, does browsing to the "log" file in a browser (http://..../logtail/log) work? It should show or download the entire log. If it does not, then you have some webserver problem (does the webserver have permission to read the file from its actual location?) which you'd need to resolve first.

**Comment by mradeschnig** [comment]
In tomcat8 context.xml need to have  <Resources allowLinking="true" />
configured.
