### ISSUE TITLE
Unable to use path to the log file

### ISSUE THREAD

**Issue by ReddySk** [ukhas/js-logtail#12]
Hello, 

when using full path to the log file I am getting error 404:
<html><body bgcolor=white><b>Object Not Found</b> (<i>apps/data/logs/support/glDBHousekeeper.log</i>)</body></html>

I have tried 
```
var url = "/apps/data/logs/support/glDBHousekeeper.log";
var url = "//apps/data/logs/support/glDBHousekeeper.log";
var url = "\/apps/data/logs/support/glDBHousekeeper.log";
```

with almost same result. Is it bug or problem between my keyboard and chair? 

Thanks, Reddy

**Comment by kpichardie** [comment]
Hello,

You should check that the url is replying, i think your web server isn't able to serve this url. 

Try curl the direct url like :

`wget localhost/apps/data/logs/support/glDBHousekeeper.log`

This should work to make logtail working.

**Comment by ReddySk** [comment]
Hello, 

yep, that's the problem. The webserver is not listening on the port 80 and almost everything is under SSL.

No problem, I will try to amend the script to work with my environment. 

Thanks, Reddy
